version: 2

sources:
  - name: helper_tables
    database: sliide-grip-prod
    schema: mdm_helper_tables
    tables:
      - name: event_config_new
      - name: session_parameters
      - name: client_mapping_events
      - name: client_mapping

models:
  - name: client_mapping_events_version
    description: ''
    tests:
      - unique:
          column_name: "(app_package_name || '-' || product)"
    columns:
      - name: product
        description: ''
        tests:
          - not_null