version: 2

models:
  - name: content-app_users
    description: 'test model name'
    columns:
      - name: user_pseudo_id
        data_type: string
        description: '{{ doc("user_pseudo_id") }}'
      - name: acquisition_date
        data_type: 'date'
        description: '{{ doc("acquisition_date") }}'
      - name: last_seen_date
        data_type: 'date'
        description: ''
      - name: activation_date
        data_type: 'date'
        description: ''
      - name: last_active_date
        data_type: 'date'
        description: ''
      - name: device_id
        data_type: 'string'
        description: ''
      - name: sliide_backend_profile_id
        data_type: 'string'
        description: ''
      - name: google_advertising_id
        data_type: 'string'
        description: ''
      - name: app_info_id
        data_type: 'string'
        description: ''
      - name: app_family_name
        data_type: 'string'
        description: ''
      - name: install_source
        data_type: 'string'
        description: ''
      - name: app_version_first_seen_string
        data_type: 'string'
        description: ''
      - name: app_version_first_seen_int
        data_type: 'integer'
        description: ''
      - name: device_type
        data_type: 'string'
        description: ''
      - name: device_make
        data_type: 'string'
        description: ''
      - name: device_model
        data_type: 'string'
        description: ''
      - name: device_screen_size_x
        data_type: 'integer'
        description: ''
      - name: device_screen_size_y
        data_type: 'integer'
        description: ''
      - name: device_os
        data_type: 'string'
        description: ''
      - name: device_os_version
        data_type: 'string'
        description: ''
      - name: device_language
        data_type: 'string'
        description: ''
      - name: tz_offset_hours
        data_type: 'float'
        description: ''
      - name: location_country
        data_type: 'string'
        description: ''
      - name: location_state
        data_type: 'string'
        description: ''
      - name: location_city
        data_type: 'string'
        description: ''
      - name: last_seen_event
        data_type: 'string'
        description: ''
      - name: last_seen_event_timestamp
        data_type: 'timestamp'
        description: ''

  - name: content-app_events
