
version: 2

models:
    - name: content-app_DAU
      description: "Daily Actyive Users (DAU) per day by product"
      columns:
          - name: event_date
            tests:
                - not_null

